name: Twitter API CI/CD Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
          # Log in to Docker Hub

    # Build the application and package it as a JAR file
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/twitter-api-demo:${{ github.sha }} .

    # Push the Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/twitter-api-demo:${{ github.sha }}

    # (Optional) Tag the image with `latest` and push again 
    - name: Tag Docker Image as latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/twitter-api-demo:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/twitter-api-demo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/twitter-api-demo:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
        image-ref: "${{ secrets.DOCKER_USERNAME }}/twitter-api-demo:latest"
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'LOW, MEDIUM,HIGH,CRITICAL'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'      
 

